-- MySQL Script generated by MySQL Workbench
-- 04/22/15 14:19:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PathfinderEncounter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PathfinderEncounter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PathfinderEncounter` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `PathfinderEncounter` ;

-- -----------------------------------------------------
-- Table `PathfinderEncounter`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathfinderEncounter`.`Book` (
  `idBook` INT NOT NULL,
  `MonsterName` VARCHAR(45) NOT NULL,
  `BookName` VARCHAR(45) NOT NULL,
  `Third Party` INT NULL,
  PRIMARY KEY (`idBook`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PathfinderEncounter`.`Monster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathfinderEncounter`.`Monster` (
  `idMonster` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `CR` INT NOT NULL,
  `Alignment` VARCHAR(20) NOT NULL,
  `Size` INT NOT NULL,
  `Class` VARCHAR(25) NULL,
  `TypeName` VARCHAR(45) NOT NULL,
  `Initiative` INT NOT NULL,
  `Armor` INT NULL,
  `Shield` INT NULL,
  `Deflection` INT NULL,
  `SizeAC` INT NULL,
  `NaturalArmor` INT NULL,
  `Dodge` INT NULL,
  `MiscAC` INT NULL,
  `HitDie` INT NOT NULL,
  `Fort` INT NOT NULL,
  `Reflex` INT NOT NULL,
  `Will` INT NOT NULL,
  `BaseSpeed` INT NOT NULL,
  `Space` INT NOT NULL,
  `Reach` INT NULL,
  `Spell-Like Abilities` VARCHAR(1500) NULL,
  `Spells` VARCHAR(1500) NULL,
  `Str` INT NULL,
  `Dex` INT NULL,
  `Con` INT NULL,
  `Inte` INT NULL,
  `Wis` INT NULL,
  `Cha` INT NULL,
  `BaseAttack` INT NOT NULL,
  `CMB` VARCHAR(45) NULL,
  `CMD` VARCHAR(45) NULL,
  `Feats` VARCHAR(1500) NULL,
  `Skills` VARCHAR(1500) NULL,
  `Languages` VARCHAR(200) NULL,
  `Special Attacks` VARCHAR(1500) NULL,
  `Environment` VARCHAR(45) NOT NULL,
  `Attack1` VARCHAR(45) NULL,
  `Attack2` VARCHAR(45) NULL,
  `Attack3` VARCHAR(45) NULL,
  `Attack4` VARCHAR(45) NULL,
  `Attack5` VARCHAR(45) NULL,
  `Book_idBook` INT NOT NULL,
  PRIMARY KEY (`idMonster`, `Book_idBook`),
  INDEX `fk_Monster_Book1_idx` (`Book_idBook` ASC),
  CONSTRAINT `fk_Monster_Book1`
    FOREIGN KEY (`Book_idBook`)
    REFERENCES `PathfinderEncounter`.`Book` (`idBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PathfinderEncounter`.`Attacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathfinderEncounter`.`Attacks` (
  `idAttacks` INT NOT NULL,
  `AttackName` VARCHAR(45) NULL,
  `D` VARCHAR(45) NOT NULL,
  `F` VARCHAR(45) NOT NULL,
  `T` VARCHAR(45) NOT NULL,
  `S` VARCHAR(45) NOT NULL,
  `M` VARCHAR(45) NOT NULL,
  `L` VARCHAR(45) NOT NULL,
  `H` VARCHAR(45) NOT NULL,
  `C` VARCHAR(45) NOT NULL,
  `G` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAttacks`),
  UNIQUE INDEX `Attack Name_UNIQUE` (`AttackName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PathfinderEncounter`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathfinderEncounter`.`Type` (
  `idType` INT NOT NULL,
  `TypeName` VARCHAR(45) NOT NULL,
  `HitDie` INT NOT NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PathfinderEncounter`.`Monster_has_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathfinderEncounter`.`Monster_has_Type` (
  `Monster_idMonster` INT NOT NULL,
  `Type_idType` INT NOT NULL,
  PRIMARY KEY (`Monster_idMonster`, `Type_idType`),
  INDEX `fk_Monster_has_Type_Type1_idx` (`Type_idType` ASC),
  INDEX `fk_Monster_has_Type_Monster1_idx` (`Monster_idMonster` ASC),
  CONSTRAINT `fk_Monster_has_Type_Monster1`
    FOREIGN KEY (`Monster_idMonster`)
    REFERENCES `PathfinderEncounter`.`Monster` (`idMonster`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Monster_has_Type_Type1`
    FOREIGN KEY (`Type_idType`)
    REFERENCES `PathfinderEncounter`.`Type` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PathfinderEncounter`.`Monster_has_Attacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PathfinderEncounter`.`Monster_has_Attacks` (
  `Monster_idMonster` INT NOT NULL,
  `Attacks_idAttacks` INT NOT NULL,
  PRIMARY KEY (`Monster_idMonster`, `Attacks_idAttacks`),
  INDEX `fk_Monster_has_Attacks_Monster1_idx` (`Monster_idMonster` ASC),
  INDEX `fk_Monster_has_Attacks_Attacks1_idx` (`Attacks_idAttacks` ASC),
  CONSTRAINT `fk_Monster_has_Attacks_Monster1`
    FOREIGN KEY (`Monster_idMonster`)
    REFERENCES `PathfinderEncounter`.`Monster` (`idMonster`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Monster_has_Attacks_Attacks1`
    FOREIGN KEY (`Attacks_idAttacks`)
    REFERENCES `PathfinderEncounter`.`Attacks` (`idAttacks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'DatabaseManager' IDENTIFIED BY 'database';

GRANT ALL ON `PathfinderEncounter`.* TO 'DatabaseManager';
GRANT SELECT ON TABLE `PathfinderEncounter`.* TO 'DatabaseManager';
GRANT SELECT, INSERT, TRIGGER ON TABLE `PathfinderEncounter`.* TO 'DatabaseManager';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `PathfinderEncounter`.* TO 'DatabaseManager';
GRANT EXECUTE ON ROUTINE `PathfinderEncounter`.* TO 'DatabaseManager';
CREATE USER 'User';

GRANT SELECT ON TABLE `PathfinderEncounter`.* TO 'User';
CREATE USER 'Engineer';

GRANT SELECT, INSERT, TRIGGER ON TABLE `PathfinderEncounter`.* TO 'Engineer';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `PathfinderEncounter`.* TO 'Engineer';
GRANT EXECUTE ON ROUTINE `PathfinderEncounter`.* TO 'Engineer';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `PathfinderEncounter`.`Book`
-- -----------------------------------------------------
START TRANSACTION;
USE `PathfinderEncounter`;
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (1, 'Camel', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (2, 'Alligator', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (3, 'Lion', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (4, 'Dire Boar', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (5, 'Hippopotamus', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (6, 'Ankylosaurus', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (7, 'Dire bear', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (8, 'giant octopus', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (9, 'dire shark', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (10, 'whale', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (11, 'fungal lizardfolk', 'Advanced Bestiary', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (12, 'yellow muskcreeper', 'Tome of Horrors', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (13, 'assassin vine', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (14, 'calathar', 'Blood for Blood', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (15, 'basirond', 'Tome of Horrors', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (16, 'mi-go', 'Monster Manual 4', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (17, 'hangman tree', 'Tome of Horrors', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (18, 'moonflower', 'Monster Manual 2', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (19, 'boruta', 'Trail of the Beast', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (20, 'giant flytrap', 'Book of Beasts', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (21, 'Ghoul', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (22, 'Draugr', 'Monster Manual 2', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (23, 'Shadow', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (24, 'Attic Whisperer', 'Monster Manual 2', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (25, 'Crypt Thing', 'Tome of Horrors', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (26, 'Phantom Lancer', 'Ashes at Dawn', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (27, 'Ghost', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (28, 'Bodak', 'Undead Revisited', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (29, 'Vampire', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (30, 'Gholdako', 'Monster Manual 4', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (31, 'Clawbat', 'The Varnhold Vanishing', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (32, 'Blindheim', 'Tome of Horrors', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (33, 'Giant Eagle', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (34, 'Devilfish', 'Monster Manual 2', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (35, 'Basilisk', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (36, 'Death Worm', 'Tome of Horrors', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (37, 'Bulette', 'Monster Manual', 0);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (38, 'Gnasher Lizard', 'Tome of Horrors', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (39, 'Dragon Horse', 'Tome of Horrors', 1);
INSERT INTO `PathfinderEncounter`.`Book` (`idBook`, `MonsterName`, `BookName`, `Third Party`) VALUES (40, 'Water Orm', 'Monster Manual 2', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `PathfinderEncounter`.`Monster`
-- -----------------------------------------------------
START TRANSACTION;
USE `PathfinderEncounter`;
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (1, 'Camel', 1, 'N', 1, '', 'Animal', 3, Null, Null, Null, -1, 1, Null, Null, 2, 5, 6, 0, 50, 10, 5, 'Null', 'Null', 18, 16, 14, 2, 11, 4, 1, '6', '19 (23 vs. trip)', 'Endurance', 'Perception +5', '', 'Spit', 'Desert', 'Bite ', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (2, 'Alligator', 2, 'N', 0, '', 'Animal', 1, Null, Null, Null, Null, 4, Null, Null, 3, 6, 4, 2, 20, 5, 5, 'Null', 'Null', 19, 12, 17, 1, 12, 2, 2, '6 (10 grapple)', '17 (21 vs trip)', 'Skill focus (Perception). Skill Focus (Stealth)', 'Perception +8. Stealth +9 (17 in water). +8 Swim', '', 'Hold Breath. Death Roll. Sprint. Swim 30', 'River. Marsh', 'Bite ', 'Tail Slap', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (3, 'Lion', 3, 'N', 1, '', 'Animal', 7, Null, Null, Null, -1, 3, Null, Null, 5, 6, 7, 2, 40, 10, 5, 'Null', 'Null', 21, 17, 15, 2, 12, 6, 3, '9 (13 grapple)', '22 (26 vs. trip)', 'Improved Initiative. Run. Skill Focus (Perception)', 'Acrobatics +11. Perception +9. Stealth +8 (12 undergrowth)', '', 'Pounch. Rake', 'Plains', 'Bite ', 'Claw', 'Claw', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (4, 'Dire Boar', 4, 'N', 1, '', 'Animal', 4, Null, Null, Null, -1, 6, Null, Null, 5, 7, 4, 2, 40, 10, 5, 'Null', 'Null', 23, 10, 17, 2, 13, 8, 3, '10', '20', 'Improved Initiative. Skill Focus (Perception). Toughness', 'Perception 12', '', 'Ferocity', 'Forest', 'Gore', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (5, 'Hippopotamus', 5, 'N', 1, '', 'Animal', 4, Null, Null, Null, -1, 8, Null, Null, 7, 8, 5, 3, 40, 10, 5, 'Null', 'Null', 19, 10, 16, 2, 13, 5, 5, '10', '20 (24 vs. trip)', 'Endurance. Improved Initiative. Power Attack. Skill Focus (Perception)', 'Perception +8. Stealth +1 (11 underwater). Swim +11', '', 'Hold Breath. Sweat. Capsize. Trample. Swim 30', 'River', 'Bite ', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (6, 'Ankylosaurus', 6, 'N', 2, '', 'Animal', 0, Null, Null, Null, -2, 14, Null, Null, 10, 12, 7, 4, 30, 15, 15, 'Null', 'Null', 27, 10, 17, 2, 13, 8, 7, '17', '27 (27 vs. trip)', 'Great Fortitude. Improved Bull Rush. Improved Overrun. Power Attack. Weapon Focus (Tail)', 'Perception +14', '', 'Stun', 'Forest. Plains', 'Tail', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (7, 'Dire bear', 7, 'N', 1, '', 'Animal', 5, Null, Null, Null, -1, 8, Null, Null, 10, 12, 8, 4, 40, 10, 5, 'Null', 'Null', 25, 13, 21, 2, 12, 10, 7, '15 (19 grapple)', '26 (30 vs trip)', 'Endurance. Improved Initiative. Iron Will. Run. Skill Focus (Perception)', 'Perception +12. Swim +19', '', 'Grab', 'Forest', 'Claw', 'Claw', 'Bite', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (8, 'giant octopus', 8, 'N', 1, '', 'Animal', 6, Null, Null, Null, -1, 7, Null, Null, 12, 11, 12, 7, 20, 10, 10, 'Null', 'Null', 20, 15, 17, 2, 12, 3, 9, '15 (19 grapple)', '27 (can\'t be tripped)', 'Combat Reflexes. Improved Initiative. Iron Will. Lightning Reflexes. Multiattack. Skill Focus (Stealth). Stealthy', 'Escape Artist +18. Perception +8. Stealth +18. Swim +13', '', 'Poison. Constrict. Grab', 'Ocean', 'Bite ', 'Tentacles', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (9, 'dire shark', 9, 'N', 3, '', 'Animal', 6, Null, Null, Null, -4, 15, Null, Null, 15, 14, 13, 8, 60, 20, 20, 'Null', 'Null', 30, 15, 17, 1, 12, 10, 11, '25 (29 grapple)', '37', 'Bleeding Critical. Critical Focus. Great Fortitude. Improved Critical (Bite). Improved Initiative. Iron Will. Lightning Reflexes. Skill Focus (Perception)', 'Perception +25. Swim +18', '', 'Blindsense 30ft. Keen Scent. Swallow Whole. Grab', 'Ocean', 'Bite ', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (10, 'whale', 10, 'N', 3, '', 'Animal', 2, Null, Null, Null, -4, 18, Null, Null, 15, 17, 7, 7, 40, 20, 20, 'Null', 'Null', 38, 6, 23, 2, 11, 5, 11, '29', '37 (Can\'t be Tripped)', 'Diehard. Endurance. Great Fortitude. Improved Bull rush. Improved Initiative. Iron will. Power Attack. Skill Focus (Perception)', 'Perception  +23. Swim +30', '', 'Hold Breath. Capsize', 'Ocean', 'Tail Slap', 'Bite', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (11, 'fungal lizardfolk', 1, 'N', 0, '', 'Plant', -1, Null, 2, Null, Null, 3, Null, Null, 2, 4, -1, 0, 30, 5, 5, 'Null', 'Null', 12, 8, 12, 8, 10, 10, 1, '2', '11', 'Multiattack', 'Acrobatics +1. Perception +1. Swim +8', 'Draconic. Sylvan', 'Plant Traits. Swim 15. Hold Breath. Poisonous Blood. Fungal Metabolism. Rejuvenation. create spawn. poison spore cloud', 'Marshes', 'Club', 'Bite', 'Claw', 'Claw', 'Bite', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (12, 'yellow muskcreeper', 2, 'N', 0, '', 'Plant', 2, Null, Null, Null, Null, 2, Null, Null, 3, 6, 3, 1, 5, 5, 10, 'Null', 'Null', 17, 15, 16, Null, 11, 8, 2, '5', '17(can\'t be tripped)', 'Null', 'Null', 'Null', 'Plant Traits. create yellow musk zombie. pollen spray', 'forest. underground', 'Tendril', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (13, 'assassin vine', 3, 'N', 1, '', 'Plant', 0, Null, Null, Null, -1, 6, Null, Null, 4, 7, 1, 2, 5, 10, 10, 'Null', 'Null', 20, 10, 16, Null, 13, 9, 3, '9 (13 grapple)', '19 (can\'t be tripped)', 'Null', 'Null', 'Null', 'Plant Traits. Immune electricity. Resist Cold 10 and Fire 10. Blindsight 30ft. low-light vision. constrict. grab. camouflage. Entangle', 'Forest', 'Slam', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (14, 'calathar', 4, 'N', -1, '', 'Plant', 8, Null, Null, Null, 1, 1, Null, Null, 6, 6, 6, 4, 20, 5, 5, 'Null', 'Null', 14, 19, 14, 6, 15, 12, 4, '5', '19 (21 vs. trip)', 'Blind-Fight. Combat Reflexes. Improved Initiative', 'Stealth +17', 'Sylvan (Cannot Speak)', 'Plant Traits. Immune Cold. Cold Healing. darkvision 30ft. low-light vision. scent. fire vulnerability. seed spray. mold mulch', 'Forest', 'Flower', 'Tendril', 'Tendril', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (15, 'basirond', 5, 'N', 0, '', 'Plant', 1, Null, Null, Null, Null, 7, Null, Null, 7, 8, 3, 2, 20, 5, 5, 'Null', 'Null', 20, 13, 16, Null, 11, 1, 5, '10', '21 (25 vs. trip)', 'Null', 'Null', 'Null', 'Plant Traits. Immune Cold. cold lethargy. low-light vision. low-light vision. tremorsense. Spores. Hallucination Cloud', 'underground', 'Slam', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (16, 'mi-go', 6, 'NE', 0, '', 'Plant', 5, Null, Null, Null, Null, 4, 1, Null, 7, 10, 7, 4, 30, 5, 5, 'Null', 'Null', 16, 20, 21, 25, 14, 15, 5, '8 (12 grapple)', '24 (32 vs. trip)', 'Combat Reflexes. Deceitful. Dodge. Weapon Finesse', 'Bluff +18. Disable Device +12. Disguise +18. fly +9. Heal +9. Knowledge (arcana. geography) +14. Perception +12. Spellcraft +14. Stealth +15', 'Akio. Common. Mi-go', 'Plant Traits. Immune Cold. DR 5/Slashing. Resist Electricity 10 and Fire 10. Fly 50. blindsight 30ft. low-light vision. Evisceration. grab. sneak attack +2d6. deceptive. item creation. no breth. starflight', 'Any', 'Claw', 'Claw', 'Claw', 'Claw', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (17, 'hangman tree', 7, 'NE', 2, '', 'Plant', 3, Null, Null, Null, -2, 13, Null, Null, 8, 12, 3, 5, 10, 15, 15, 'Null', 'Null', 25, 8, 23, 7, 12, 10, 6, '15 (19 grapple)', '24', 'Improved Initiative. Iron Will. Lightning Reflexes. Skill Focus (Perception)', 'Perception +11. Stealth -2', 'Sylvan', 'Plant Traits. SR 18. blindsight 60ft. vulnerable to electricity. grab. pull. constrict. hallucinatory spores. pull. strangle. swallow whole. vines', 'Forest', 'Vine', 'Vine', 'Vine', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (18, 'moonflower', 8, 'N', 2, '', 'Plant', 4, Null, Null, Null, -2, 13, Null, Null, 11, 12, 3, 4, 20, 15, 15, 'Null', 'Null', 28, 10, 21, 5, 12, 17, 8, '19 (23 grapple)', '29 (can\'t be tripped)', 'Blind-Fight. Improved Initiative. Improved Sunder. Multiattack. Power Attack. Skill Focus (Stealth)', 'Perception +9. Stealth +4 (20 in thick vegetation)', 'telepathy (1 mile other moonflowers)', 'Plant Traits. Immune electricity. Resist Cold 10. vulnerable to fire. DR 10/slashing. darkvision 60ft. low-light vision. grab. light pulse. pod prison. telepathy. pod spawn', 'Any', 'Bite', 'Tentacle', 'Tentacle', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (19, 'boruta', 9, 'N', 0, '', 'Plant', 6, Null, Null, Null, Null, 10, 1, Null, 14, 12, 6, 7, 20, 5, 5, '(CL 7th. Concentration 10) Constant -- pass without trace. At will -- entangle (DC 14). 3/day -- command plants (DC17). 1/day -- Summon nature\'s ally V (1 shambling mount only)', '(CL 7th. concentration +10). 4th -- Spike stones (DC 17). 3rd -- call lightning (2. DC 16). plant growth. 2nd -- fog Cloud. soften earth and stone. tree shape. wood shape (DC 15). 1st -- calm animals. detect animals or plants. goodberry. magic fang. speak with animals. 0th -- create water. detect magic. detect poison. know direction. mending', 17, 15, 16, 13, 17, 16, 10, '13', '26', 'Combat Casting. Combat Reflexes. Dodge. Improved Initiative. Improved Iron Will. Mobility. Natural Spell', 'Perception +20. Stealth +19. Survival +17', 'Common. Sylvan', 'Plant Traits. Immune electricity. low-light vision. grounding curse. treespeech. wild shape. Electric Fortitude', 'Any', 'Claw', 'Claw', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (20, 'giant flytrap', 10, 'N', 2, '', 'Plant', 8, Null, Null, Null, -2, 10, Null, Null, 13, 17, 8, 5, 10, 15, 15, 'Null', 'Null', 25, 18, 25, 1, 12, 6, 9, '18 (22 grapple)', '32 (Can\'t be tripped)', 'Cleave. Great Fortitude. Improved Initiative. Power Attack. Skill Focus (Stealth). Vital Strike. Weapon Focus (bite)', 'Perception +10. Sealth +9 (17 in undergrowth)', '', '(Immune to mind-affecting effects. paralysis. poison. polymorph. sleep. stun). Resist Acid 20. low-light vision. tremorsense 60ft. grab. engulf', 'Swamp', 'Bite', 'Bite', 'Bite', 'Bite', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (21, 'Ghoul', 1, 'CE', 0, '', 'Undead', 2, Null, Null, Null, Null, 2, Null, Null, 2, 2, 2, 5, 30, 5, 5, 'Null', 'Null', 12, 15, Null, 13, 14, 14, 1, '2', '14', 'Weapon Finesse', 'Acrobatics +4. Climb +6. Perception +7. Stealth +7. Swim +3', 'Common', 'Channel Resistance +2. Undead Traits. Paralysis. Disease(Ghoul Fever)', 'Any Land', 'Bite', 'Claw', 'Claw', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (22, 'Draugr', 2, 'CE', 0, '', 'Undead', 0, 2, Null, Null, Null, 2, Null, Null, 3, 2, 1, 3, 30, 5, 5, 'Null', 'Null', 17, 10, Null, 8, 10, 13, 2, '5', '15', 'Power Attack. Toughness', 'Climb +9. Perception +6. Stealth +6. Swim +11', 'Common', 'Swim 30. Darkvision. DR 5/Bludgeoning or slashing. Undead Traits. Resist Fire 10. Nausea', 'Coastal', 'Great Axe', 'Slam', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (23, 'Shadow', 3, 'CE', 0, '', 'Undead', 2, Null, Null, 2, Null, Null, 1, Null, 3, 3, 3, 4, 40, 5, 5, 'Null', 'Null', -1, 14, Null, 6, 12, 15, 2, '4', '17', 'Dodge. Skill Focus (Perception)', 'Fly +11. Perception +8. Stealth +8 (+12 in dim light. +4 in bright light)', 'Common', 'Fly 40. Incorporeal. Undead Traits. Channel Resistance +2', 'Any', 'Incorporeal Touch', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (24, 'Attic Whisperer', 4, 'NE', 0, '', 'Undead', 8, Null, Null, Null, 1, 3, 1, Null, 6, 5, 6, 8, 20, 5, 5, 'Null', 'Null', 9, 19, Null, 14, 16, 17, 4, '2', '17', 'Dodge. Improved Initiative. Weapon Finesse', 'Bluff +9. Climb +8. Knowledge(History) +8 . Knowledge(local) +8. Perception +12. Stealth +17', 'Common(plus any 2d4 from victims)', 'Dark Vision. Steal Voice. Aura of Sobs. Steal Breath', 'Any', 'Bite', 'Touch', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (25, 'Crypt Thing', 5, 'NE', 0, '', 'Undead', 6, Null, Null, Null, Null, 6, 1, Null, 8, 4, 6, 8, 30, 5, 5, '(CL 8th; Concentration +10) 3/day—Quickened Dimension Door', '', 19, 14, Null, 13, 14, 15, 6, '10', '23', 'Alertness. Dodge. Improved Initiative. Lightning Reflexes', 'Bluff +6. Intimidate +13. Knowledge(arcana) +6. Knowledge (dungeoneering) +5. Knowledge (history) +3. Perception +15. Sense Motive +15. Stealth +9', 'Common', 'Dark Vision. Low-light Vision. Fear Aura)(10 ft. Frightened for 1d4 Rounds. Will DC 16 Negates). Channel Resistance +2. DR 10/bludgeoning or magic. Undead Traits. Teleporting Burst', 'underground', 'Claw', 'Claw', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (26, 'Phantom Lancer', 6, 'NE', 1, '', 'Undead', 6, 9, 2, Null, -1, Null, Null, Null, 9, 7, 5, 6, 40, 10, 10, 'Null', 'Null', 17, 15, Null, 7, 11, 18, 6, '10', '22', 'Dodge. Flyby Attack. Improved Initiative. Power Attack. Mobility', 'Perception +12. Stealth +10', 'Common', 'Armor Rider. Freeze. Dark Vision. Channel Resistance +4. Undead Traits. Trample', 'Any', 'Mwk Lance', 'Long Bow', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (27, 'Ghost', 7, 'CE', 0, 'Aristocrat 7', 'Undead', 5, Null, Null, 5, Null, Null, 1, Null, 7, 7, 5, 7, 30, 5, 5, 'Null', 'Null', -1, 12, Null, 10, 11, 20, 5, '5', '22', 'Dodge. Improved Initiative. Iron Will. Lightning Reflexes. Toughness.', 'Fly +9. Knowledge(histoy) +10. Knowledge(nobility) +10. Perception +18. Sense Motive +10. Stealth +9', 'Common', 'Dark Vision. Channel Resistance +4. Incorporeal. Rejuvenation. Undead Traits. Corrupting Touch. Frightful Moan.', 'Any', 'Touch', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (28, 'Bodak', 8, 'CE', 0, '', 'Undead', 6, Null, Null, Null, Null, 8, 1, Null, 10, 6, 5, 8, 20, 5, 5, 'Null', 'Null', 13, 15, Null, 6, 13, 16, 7, '8', '21', 'Dodge. Improved Initiative. Mobility . Toughness. Weapon Focus(slam)', 'Intimidate +11. Perception +14. Stealth +10', 'Common', 'Dark Vision. DR 10/Cold Iron. Immune Electricity. Undead Traits. Resist Acid 10. Resist Fire 10. Vulnerable to Sunlight. Death Gaze', 'Any', 'Slam', 'Slam', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (29, 'Vampire', 9, 'CE', 0, 'Sorcerer 8', 'Undead', 8, Null, Null, 2, Null, 6, 1, Null, 8, 13, 11, 12, 30, 5, 5, '(CL 8th; +7 Touch) 11/day – Grave Touch', '(CL 8th. +8 Ranged Touch) 4th (5/day) – Greater Invisibilty; 3rd(5/day) – Dispel Magic. Fireball(DC 21). Vampiric Touch; 2nd(8/day) – False Life. Invisibility. Scorching Ray. Web(DC 20); 1st(8/day) – Buring Hands(DC19). Chill Touch(DC 19). Disguise Self. Expedition Retreat. Mage Armor. Magic Missile; 0 – Acid Splash. Detect Magic. Light. Mage Hand. Mending. Message. open/close. Read Magic; Bloodline – Undead', 16, 18, Null, 14, 16, 26, 4, '7', '24', 'Alertness. Blind-Fight. Combat Casting. Combat Relexes. Dodge. Eschew Materials. Extend Spell. Improved Initiative. Lightning Reflexes. Silent Spell. Still Spell. Toughness. Weapon Finess', 'Bluff +27. Knowledge(arcana) +13. Knowledge(religion) +10. Perception +21. Sense Motive +13. Spellcraft +13. Stealth +12. Use Magic Device +19', 'Abyssal. Common. Draconic', 'Dark Vision. Channel Resistance +4. DR 10/Magic and Silver. Undead Traits. Resist Cold 10. Resist Electricity 10. Vampire Weaknesses. Blood Drain. Change Shape. Children of the Night. Create Spawn. Dominate. Energy Drain. Gaseous Form. Shadowless. Spider Climb', 'Any', 'Slam', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (30, 'Gholdako', 10, 'NE', 1, '', 'Undead', 0, Null, Null, Null, -1, 16, Null, Null, 15, 9, 5, 10, 30, 10, 10, 'Null', 'Null', 25, 10, Null, 10, 13, 19, 11, '19 (21 Bull Rush)', '29 (31 vs Bull Rush)', 'Awesome Blow. Cleave. Critical Focus. Great Cleave. Improved Bull Rush. Improved Critical(Claw). Power Attack. Weapon Focus(Claw)', 'Intimidate +22. Knowledge(history) +8. Perception +19. Sense Motive +11. Stealth +14', 'Giant', 'Dark Vision. Low-light Vision. Channel Resistance +3. DR 5/good. Undead Traits. Resist Cold 10. Resist Fire 10. Blinding Breath. Desease', 'Coastal', 'Bite', 'Claw', 'Claw', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (31, 'Clawbat', 1, 'N', -1, '', 'Magical Beast', 3, 1, Null, Null, 1, Null, Null, Null, 2, 3, 6, 2, 10, 5, 5, 'Null', 'Null', 7, 17, 10, 2, 14, 10, 2, '-1', '12', 'Flyby Attack. Weapon Finesse', 'Fly +5. Stealth +12', '', 'Blood Scent. Distration. bleed', 'hills', 'Bite', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (32, 'Blindheim', 2, 'N', -1, '', 'Magical Beast', 2, Null, Null, Null, 1, 2, 1, Null, 3, 5, 5, 2, 30, 5, 5, 'Null', 'Null', 13, 15, 15, 2, 12, 6, 3, '3', '16', 'Dodge. Skill Focus (Perception)', 'Acrobatics +6(+10 jump). Perception +9. Swim +9', '', 'Blinding Gaze. Immune Blindness', 'underground', 'Bite', 'Claw', 'Claw', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (33, 'Giant Eagle', 3, 'NG', 1, '', 'Magical Beast', 3, Null, Null, Null, -1, 3, Null, Null, 4, 5, 7, 3, 10, 10, 5, 'Null', 'Null', 18, 17, 12, 10, 15, 11, 4, '9', '22', 'Alertness. Flyby Attack', 'Fly +8. Perception +15. Sense Motive +4', 'Auran', 'Fly 80', 'mountains', 'Claw', 'Claw', 'Bite', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (34, 'Devilfish', 4, 'NE', 1, '', 'Magical Beast', 3, Null, Null, Null, -1, 5, Null, Null, 5, 7, 7, 2, 10, 10, 5, 'Null', 'Null', 17, 17, 16, 3, 12, 8, 5, '9 (13 grapple)', '22 (can\'t be tripped)', 'Cleave. Combat Reflexes. Power Attack', 'Escape Artist +5. Perception +5. Stealth +3. Swim +15', 'Abyssal. Aquan. Common', 'Swim 40. Poison. Savage Bite. Unholy Blood. Water Dependency', 'aquatic', 'Tentacles', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (35, 'Basilisk', 5, 'N', 0, '', 'Magical Beast', -1, Null, Null, Null, Null, 8, Null, Null, 7, 9, 4, 5, 20, 5, 5, 'Null', 'Null', 16, 8, 15, 2, 13, 11, 7, '10', '19 (31 vs trip)', 'Blind-Fight. Great Fortitude. Iron Will. Skill Focus(Perception)', 'Perception +10. Stealth +10', '', 'Gaze', 'any', 'Bite', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (36, 'Death Worm', 6, 'N', 1, '', 'Magical Beast', 1, Null, Null, Null, -1, 9, Null, Null, 8, 9, 7, 4, 20, 10, 5, 'Null', 'Null', 18, 13, 16, 3, 11, 5, 8, '13', '24', 'Cleave. Improved Overrun. Iron Will. Power Attack', 'Perception +11. Stealth -3 (+13 in deserts)', 'Terran', 'Corrosive Blood. Electrical Jolt. Poison. Venomous Skin', 'desert', 'Bite', 'Electric Jolt', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (37, 'Bulette', 7, 'N', 2, '', 'Magical Beast', 6, Null, Null, Null, -2, 12, Null, Null, 8, 11, 8, 5, 40, 15, 10, 'Null', 'Null', 23, 15, 20, 2, 13, 6, 8, '16', '28(32 vs trip)', 'Improved Initiative. Iron Will. Skill Focus(Perception). Weapon Focus(Bite)', 'Acrobatics +9(+17 Jumping) Perception +11', '', 'Leap. Savage Bite. Burrow 20', 'hills', 'Bite', 'Claw', 'Claw', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (38, 'Gnasher Lizard', 8, 'N', 1, '', 'Magical Beast', 7, Null, Null, Null, -1, 9, Null, Null, 10, 12, 8, 4, 30, 10, 5, 'Null', 'Null', 24, 16, 20, 2, 12, 10, 10, '18 (22 grapple)', '31(35 vs Trip)', 'Improved Initiative. Power Attack. Skill Focus(Perception). Vital Strike. Weapon Focus(bite)', 'Perception +16. Stealth +11', '', 'Vorpal Bite. Swallow Whole', 'forests', 'Bite', 'Null', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (39, 'Dragon Horse', 9, 'NG', 1, '', 'Magical Beast', 7, Null, Null, Null, -1, 10, 1, Null, 10, 12, 10, 9, 60, 10, 10, 'Null', 'Null', 24, 17, 21, 16, 18, 21, 10, '18', '32(36 vs Trip)', 'Dodge. Flyby Attack. Improved Initiative. Iron Will. Mobility', 'Fly +18. Knowledge(planes) +13. Perception +17. Sense Motive +14. Survival +14', 'Auran. Common. Draconic. Telepathy', 'Know Alignment. Breath Weapon. Fly 120. Flying Charge. Shift Planes', 'any', 'Hoove', 'Hoove', 'Null', 'Null', 'Null', DEFAULT);
INSERT INTO `PathfinderEncounter`.`Monster` (`idMonster`, `Name`, `CR`, `Alignment`, `Size`, `Class`, `TypeName`, `Initiative`, `Armor`, `Shield`, `Deflection`, `SizeAC`, `NaturalArmor`, `Dodge`, `MiscAC`, `HitDie`, `Fort`, `Reflex`, `Will`, `BaseSpeed`, `Space`, `Reach`, `Spell-Like Abilities`, `Spells`, `Str`, `Dex`, `Con`, `Inte`, `Wis`, `Cha`, `BaseAttack`, `CMB`, `CMD`, `Feats`, `Skills`, `Languages`, `Special Attacks`, `Environment`, `Attack1`, `Attack2`, `Attack3`, `Attack4`, `Attack5`, `Book_idBook`) VALUES (40, 'Water Orm', 10, 'N', 2, '', 'Magical Beast', 7, Null, Null, Null, -2, 13, Null, Null, 13, 13, 13, 7, 20, 15, 15, 'Null', 'Null', 26, 16, 21, 4, 13, 11, 13, '23(27 grapple)', '36(40 vs trip)', 'Improved Critical(bite). Improved Initiative. Improved Iron Will. Iron Will. Lightning Reflexes. Power Attack. Skill Focus(Stealth)', 'Perception +11. Stealth +14. Swim +16', 'Aquan', 'Elusive. Water Travel. Swallow Whole', 'lake', 'Bite', 'Tail Slap', 'Null', 'Null', 'Null', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `PathfinderEncounter`.`Attacks`
-- -----------------------------------------------------
START TRANSACTION;
USE `PathfinderEncounter`;
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (1, 'Bite', '1', '1d2', '1d3', '1d4', '1d6', '1d8', '2d6', '2d8', '4d6');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (2, 'Tail Slap', '1', '1d2', '1d3', '1d4', '1d6', '1d8', '2d6', '2d8', '4d6');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (3, 'Claw', '0', '1', '1d2', '1d3', '1d4', '1d6', '1d8', '2d6', '2d8');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (4, 'Gore', '1', '1d2', '1d3', '1d4', '1d6', '1d8', '2d6', '2d8', '4d6');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (5, 'Tentacles', '0', '1', '1d2', '1d3', '1d4', '1d6', '1d8', '2d6', '2d8');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (6, 'Club', '1', '1d2', '1d3', '1d4', '1d6', '1d8', '2d6', '3d6', '4d6');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (7, 'Tendril', '0', '1', '1d2', '1d3', '1d4', '1d6', '1d8', '2d6', '2d8');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (8, 'Slam', '0', '1', '1d2', '1d3', '1d4', '1d6', '1d8', '2d6', '2d8');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (9, 'Flower', '1d2', '1d3', '1d4', '1d6', '2d4', '2d6', '3d6', '4d6', '6d6');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (10, 'Vine', '0', '0', '1', '1d2', '1d3', '1d4', '1d6', '1d8', '2d6');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (11, 'Great Axe', '1d4', '1d6', '1d8', '1d10', '1d12', '3d6', '4d6', '6d6', '8d6');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (12, 'Incorporeal Touch', '1', '1d2', '1d3', '1d4', '1d6', '1d8', '2d6', '3d6', '4d6');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (13, 'Touch', '2d6', '3d6', '4d6', '6d6', '7d6', '8d6', '12d6', '18d6', '27d6');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (14, 'Mwk Lance', '1d2', '1d3', '1d4', '1d6', '1d8', '2d6', '3d6', '4d6', '6d6');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (15, 'Long Bow', '1d2', '1d3', '1d4', '1d6', '1d8', '2d6', '3d6', '4d6', '6d6');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (16, 'Electric Jolt', '1d6', '1d8', '1d10', '2d6', '3d6', '4d6', '6d6', '8d6', '12d6');
INSERT INTO `PathfinderEncounter`.`Attacks` (`idAttacks`, `AttackName`, `D`, `F`, `T`, `S`, `M`, `L`, `H`, `C`, `G`) VALUES (17, 'Hoove', '0', '1', '1d2', '1d3', '1d4', '1d6', '1d8', '2d6', '2d8');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PathfinderEncounter`.`Type`
-- -----------------------------------------------------
START TRANSACTION;
USE `PathfinderEncounter`;
INSERT INTO `PathfinderEncounter`.`Type` (`idType`, `TypeName`, `HitDie`) VALUES (1, 'Animal', 8);
INSERT INTO `PathfinderEncounter`.`Type` (`idType`, `TypeName`, `HitDie`) VALUES (2, 'Plant', 8);
INSERT INTO `PathfinderEncounter`.`Type` (`idType`, `TypeName`, `HitDie`) VALUES (3, 'Undead', 8);
INSERT INTO `PathfinderEncounter`.`Type` (`idType`, `TypeName`, `HitDie`) VALUES (4, 'Magical Beast', 10);

COMMIT;

USE `PathfinderEncounter`;

DELIMITER $$
USE `PathfinderEncounter`$$
CREATE DEFINER = DatabaseManager TRIGGER `PathfinderEncounter`.`Monster_BEFORE_INSERT` BEFORE INSERT ON `Monster` 
FOR EACH ROW
Begin
	DECLARE msg VARCHAR(255);
    DECLARE found_it INT;
    IF NEW.size < -4 OR NEW.size > 4 THEN
		set msg = "Error: Size categories must be an integer between -4 and 4";
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;
        
	IF NEW.alignment <> 'LG' AND NEW.alignment <> 'NG' AND NEW.alignment <> 'CG' AND NEW.alignment <> 'LN' AND NEW.alignment = 'N' AND NEW.alignment <> 'CN' AND NEW.alignment <> 'LE' AND NEW.alignment <> 'NE' AND NEW.alignment <> 'CE' Then
        set msg = "Error: Invalid input for alignment";
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;
        
    IF NEW.CR < 1 OR NEW.CR > 10 THEN
		set msg = "Error: CR must be an integer between 1 and 10";
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;   
        
    IF NEW.Armor < 0 OR NEW.Shield < 0 OR New.Deflection < 0 OR NEW.NaturalArmor < 0 OR NEW.Dodge < 0 OR New.MiscAC < 0 Then   
        set msg = "Error: All Armor Class values must be greater than 0";
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;  
        
    IF NEW.HitDie < 0 OR NEW.BaseSpeed < 0 OR New.Space < 0 OR NEW.Reach < 0 Then   
        set msg = "Error: Hit Die, Speed, Space, and Reach must be nonnegative";
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;  
        
      IF NEW.STR < 0 OR NEW.DEX < 0 OR New.CON < 0 OR NEW.INTE < 0 OR New.WIS < 0 OR NEW.CHA < 0 Then   
        set msg = "Error: Stats must be nonnegative";
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;
      
      if new.attack1 is not null then
      SELECT COUNT(1) INTO found_it FROM Attacks
        WHERE AttackName = NEW.Attack1;
        IF found_it = 0 THEN
			set msg = new.attack1;
			-- set msg = "Error: Attack1 type not in database. Contact Database Manager for Assistance";
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg; 
        END IF;
        end if;
      
      if new.attack2 is not null then
	  SELECT COUNT(1) INTO found_it FROM Attacks
        WHERE AttackName = NEW.Attack2;
        IF found_it = 0 THEN
			set msg = "Error: Attack2 type not in database. Contact Database Manager for Assistance";
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg; 
        END IF;
        end if; 
       
      if new.attack3 is not null then 
      SELECT COUNT(1) INTO found_it FROM Attacks
        WHERE AttackName = NEW.Attack3;
        IF found_it = 0 THEN
			set msg = "Error: Attack3 type not in database. Contact Database Manager for Assistance";
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg; 
        END IF;
        end if;
      
      if new.attack4 is not null then
      SELECT COUNT(1) INTO found_it FROM Attacks
        WHERE AttackName = NEW.Attack4;
        IF found_it = 0 THEN
			set msg = "Error: Attack4 type not in database. Contact Database Manager for Assistance";
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg; 
        END IF;
        end if;
      
      if new.attack5 is not null then
  	  SELECT COUNT(1) INTO found_it FROM Attacks
        WHERE AttackName = NEW.Attack5;
        IF found_it = 0 THEN
			set msg = "Error: Attack5 type not in database. Contact Database Manager for Assistance";
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg; 
        END IF;  
        end if;
        END;$$

USE `PathfinderEncounter`$$
CREATE DEFINER = DatabaseManager TRIGGER `PathfinderEncounter`.`Monster_BEFORE_UPDATE` BEFORE UPDATE ON `Monster` FOR EACH ROW
    Begin
	DECLARE msg VARCHAR(255);
    DECLARE found_it INT;
    IF NEW.size < -4 OR NEW.size > 4 THEN
		set msg = "Error: Size categories must be an integer between -4 and 4";
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;
        
	IF NEW.alignment <> 'LG' OR NEW.alignment <> 'NG' OR NEW.alignment <> 'CG' OR NEW.alignment <> 'LN' OR NEW.alignment <> 'N' OR NEW.alignment <> 'CN' OR NEW.alignment <> 'LE' OR NEW.alignment <> 'NE' OR NEW.alignment <> 'CE' Then
		set msg = "Error: Invalid input for alignment";
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;
        
    IF NEW.CR < 1 OR NEW.CR > 10 THEN
		set msg = "Error: Size categories must be an integer between -4 and 4";
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;   
        
    IF NEW.Armor < 0 OR NEW.Shield < 0 OR New.Deflection < 0 OR NEW.NaturalArmor < 0 OR NEW.Dodge < 0 OR New.MiscAC < 0 Then   
        set msg = "Error: All Armor Class values must be greater than 0";
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;  
        
    IF NEW.HitDie < 0 OR NEW.BaseSpeed < 0 OR New.Space < 0 OR NEW.Reach < 0 Then   
        set msg = "Error: Hit Die, Speed, Space, and Reach must be nonnegative";
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;  
        
      IF NEW.STR < 0 OR NEW.DEX < 0 OR New.CON < 0 OR NEW.INTE < 0 OR New.WIS < 0 OR NEW.CHA < 0 Then   
        set msg = "Error: Stats must be nonnegative";
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;
        
      SELECT COUNT(1) INTO found_it FROM Attacks.AttackName
        WHERE AttackName = NEW.Attack1;
        IF found_it = 0 THEN
			set msg = "Error: Attack type not in database. Contact Database Manager for Assistance";
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg; 
        END IF;
        
	  SELECT COUNT(1) INTO found_it FROM Attacks.AttackName
        WHERE AttackName = NEW.Attack2;
        IF found_it = 0 THEN
			set msg = "Error: Attack type not in database. Contact Database Manager for Assistance";
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg; 
        END IF;
        
      SELECT COUNT(1) INTO found_it FROM Attacks.AttackName
        WHERE AttackName = NEW.Attack3;
        IF found_it = 0 THEN
			set msg = "Error: Attack type not in database. Contact Database Manager for Assistance";
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg; 
        END IF;
      
      SELECT COUNT(1) INTO found_it FROM Attacks.AttackName
        WHERE AttackName = NEW.Attack4;
        IF found_it = 0 THEN
			set msg = "Error: Attack type not in database. Contact Database Manager for Assistance";
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg; 
        END IF;
        
  	  SELECT COUNT(1) INTO found_it FROM Attacks.AttackName
        WHERE AttackName = NEW.Attack5;
        IF found_it = 0 THEN
			set msg = "Error: Attack type not in database. Contact Database Manager for Assistance";
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg; 
        END IF;      
        END;$$

USE `PathfinderEncounter`$$
CREATE DEFINER = CURRENT_USER TRIGGER `PathfinderEncounter`.`Type_BEFORE_INSERT` BEFORE INSERT ON `Type` FOR EACH ROW
Begin
	DECLARE msg VARCHAR(255);
    
    IF NEW.HitDie < 1 THEN
		set msg = "Error: Size of Hit Die must be greater than 0";
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;
        END;
            $$

USE `PathfinderEncounter`$$
CREATE DEFINER = CURRENT_USER TRIGGER `PathfinderEncounter`.`Type_BEFORE_DELETE` BEFORE DELETE ON `Type` FOR EACH ROW
 begin
 	DECLARE msg VARCHAR(255);
    DECLARE found_it INT;
    
       SELECT COUNT(1) INTO found_it FROM Monster.TypeName, Type.TypeName
        WHERE Type.TypeName = Monster.TypeName;
        IF found_it = 0 THEN
			set msg = "Error: Monster in database has type and must be deleted before type can be removed";
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg; 
        END IF;
        End;$$


DELIMITER ;
